server {
    listen 8080 ;
    server_name localhost;

    root /var/www/nginx-hello;
    index index.html ;


    location / {
        try_files $uri $uri/ =404;

    }


    access_log /var/log/nginx/nginx-hello.access.log;
    error_log /var/log/nginx/nginx-hello.error.log;
}
